a = xout(1);
b = xout(2);
c = xout(3);
x = xout(4);
y = xout(5);
z = xout(6);
T = [1 0 0 x;...
     0 1 0 y;...
     0 0 1 z;...
     0 0 0 1];
 Ra = [1,   0,        0,        0;...
       0,   cosd(a),  sind(a),  0;...
       0,   -sind(a), cosd(a),  0;...
       0    0         0         1];
 Rb = [cosd(b),  0,  sind(b), 0;...
       0        1   0       0;...
       -sind(b), 0,  cosd(b), 0;...
       0        0   0       1];
 Rc = [cosd(c),   sind(c),  0, 0;...
       -sind(c),  cosd(c),  0, 0;...
       0,         0,        1, 0;...
       0,         0,        0, 1];
 A = Ra*Rb*Rc*T;
%  Ps1 = zeros(1,4);  %机床坐标系测算的点
 Ps1 = (A*Pw')';
 
 close %关闭之前的图像 
 
 plot3(Ps(:,1),Ps(:,2),Ps(:,3),'.','Color','r')
 hold on;
%  plot3(Pw(:,1),Pw(:,2),Pw(:,3),'.','Color','b')
 plot3(Ps1(:,1),Ps1(:,2),Ps1(:,3),'.','Color','g')
 axis equal;
 error = ErrorDistance(Ps1,Pw)