function [ pointOut ] = Inverse( x,y,z,a,b,c,pointIn )
%指定动平台变换矩阵参数x,y,z,a,b,c，计算动平台上的点pointIn在绝对坐标系下的坐标pointOut
%动平台运动变换顺序是平移-俯仰-横滚-偏航

%原点平移
T = [1 0 0 x;...
     0 1 0 y;...
     0 0 1 z;...
     0 0 0 1];
 %俯仰 YAW
 Ra = [1,   0,          0,          0;...
       0,   cosd(a),    -sind(a),   0;...
       0,   sind(a),    cosd(a),    0;...
       0    0           0           1];
 %横滚 ROLL
 Rb = [cosd(b),     0,  sind(b),    0;...
       0            1   0           0;...
       -sind(b),    0,  cosd(b),    0;...
       0            0   0           1];
%偏航
 Rc = [cosd(c),     -sind(c),  0, 0;...
       sind(c),     cosd(c),   0, 0;...
       0,           0,         1, 0;...
       0,           0,         0, 1];
 [dim, ~] = size(pointIn);
 pointOut = zeros(dim, 4);
 for index = 1 : dim
    pointOut(index,:) = ( T * Rc * Rb * Ra * pointIn(index, :)')';
 end
end

