function [ pointCloudOut ] = RotatePointCloud( pointCloudIn, a, b, c )
%将点云进行旋转变换

    Ra = [ 1,   0,         0,         0;...
           0,   cosd(a),   -sind(a),  0;...
           0,   sind(a),   cosd(a),   0;...
           0,   0,         0,         1];
    Rb = [ cosd(b),    0,   sind(b),  0;...
           0,          1,  0,         0;...
           -sind(b),   0,  cosd(b),   0;...
           0,          0,  0,         1];
    Rc = [ cosd(c),    -sind(c), 0,  0;...
           sind(c),   cosd(c),   0,  0;...
           0,         0,         1,  0;...
           0,         0,         0,  1];

    pointCloudOut = zeros(size(pointCloudIn));
    for i = 1 : length(pointCloudIn)
        p1 = [pointCloudIn(i, :), 1]';
        p2 = Rc * Rb * Ra * p1;
        pointCloudOut(i, :) = p2(1:3)';
    end

end

