//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UltrasonicImmersedTest.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_VIEW_CHANNEL_INFO            101
#define IDS_CHANNEL_TOOLBAR             102
#define IDD_MOVEPATHVIEW                103
#define IDS_MECHANICAL_TOOLBAR          104
#define IDS_CSCANPARAM_TOOLBAR          105
#define IDS_MAIN_TOOLBAR                106
#define IDD_MSGDLG                      107
#define IDR_MAINFRAME                   128
#define IDR_UltrasonicImmerTYPE         129
#define IDD_CHANNEL_PANEL               130
#define IDD_DIALOG1                     131
#define IDD_MECHANICAL_CONTROL          131
#define IDI_ICON_Z_DOWN                 134
#define IDI_ICON_Y_FRONT                135
#define IDI_ICON_Z_UP                   136
#define IDI_ICON_X_LEFT                 137
#define IDI_ICON_X_RIGHT                138
#define IDI_ICON6                       139
#define IDI_ICON_Y_BACK                 139
#define IDB_BITMAP1                     141
#define IDB_BITMAP2                     142
#define IDB_BITMAP3                     143
#define IDR_TOOLBAR1                    144
#define IDB_BITMAP4                     145
#define IDB_BITMAP5                     147
#define IDR_TOOL_VIEW                   158
#define IDR_TOOL_DRAW1                  158
#define IDR_TOOL_DRAW                   158
#define IDR_TOOLBAR2                    160
#define IDR_TOOLBAR_VIEW                160
#define IDR_TOOLB_VIEW                  160
#define IDB_BITMAP6                     161
#define IDR_TOOL_STANDARD               162
#define IDD_SYS_PARAM                   165
#define IDD_DIALOG_SETSTEP              166
#define IDD_CSCANPARAM_PANEL            167
#define IDD_DLG_SMOOTH                  168
#define IDD_DIG_MIDFILTER               169
#define IDD_DIG_GEOMROTA                170
#define IDD_DLG_GEOZOOM                 171
#define IDD_DIALOG_DAC_MAKE             173
#define IDD_DIALOG2                     173
#define IDD_DIALOG_PROBE_INFO           173
#define IDD_DIALOG3                     174
#define IDD_DIALOG_SAVE_PARAM_DEFINE    174
#define IDD_CSCAN_DLGBAR                175
#define IDD_DIALOG_SURFACE_DETAIL       176
#define IDB_ARROWUP                     178
#define IDD_DIALOG_LOG_ON               178
#define IDB_ARROWDOWN                   179
#define IDD_DIALOG_DAC_CURVE            180
#define IDD_DIALOG4                     181
#define IDD_DIALOG_GRAYVALUE            181
#define IDD_BSCANPARAM_PANEL            182
#define IDD_DIALOG_PROBE_LOCATION       183
#define IDD_DIALOG_HANHE_RATE           184
#define IDD_DIALOG_MESSAGE              185
#define IDD_DIALOG_ORIGIN               186
#define IDR_MENU_CSCAN_POPUP            188
#define IDD_DIALOG_TCG_CURVE            189
#define IDR_TOOL_CHANNEL                190
#define IDR_TOOL_MECHANICAL             191
#define IDR_TOOL_CSCANPARAM             192
#define IDD_DIALOG_DEFECT               193
#define IDD_DIALOG_PIPE_PARAM           195
#define IDD_DIALOG_TASK                 197
#define IDD_DIALOG_TASK_NAME            198
#define IDD_DIALOG_TASK_INFO            198
#define IDD_DIALOG_TASK_ITEM            199
#define IDI_ICON_Y_INCREASE_REVERSE     200
#define IDI_ICON_X_DECREASE_REVERSE     201
#define IDI_ICON_X_INCREASE_REVERSE     202
#define IDI_ICON4                       203
#define IDI_ICON_Y_DECREASE_REVERSE     203
#define IDD_DIALOG_CUSTUM_SURFACE_DEFINE 204
#define IDR_MENU_CUSTUM_SURFACE         205
#define IDD_DIALOG_EDGE_DB              206
#define IDB_BITMAP7                     207
#define IDD_DIALOG_WEIJIANGUAN_PARAM    207
#define IDR_MENU_HA_FEI                 208
#define IDD_DIALOG_DROPFAULT            209
#define IDD_DIALOG_WEIJIANGUAN_SKETCH   210
#define IDD_DIALOG_WEIJIANGUAN_UNFOLD   211
#define IDD_DIALOG_PART_GAIN_COMPENSATE 212
#define IDB_BITMAP8                     213
#define IDB_WEIJIANGUAN_SKETCH          213
#define IDC_BUTTON_Y_FRONT              1000
#define IDC_BUTTON_X_LEFT               1001
#define IDC_GRAPHMOVECTRL1              1001
#define IDC_GRAPHMOVECTRL               1001
#define IDC_BUTTON_Y_BACK               1002
#define IDC_BUTTON_X_RIGHT              1003
#define IDC_BUTTON_UP_Z                 1004
#define IDC_BUTTON_Z_DOWN               1005
#define IDC_BUTTON_REPOSITION           1006
#define IDC_BUTTON_RUN                  1007
#define IDC_EDIT_XCOORD                 1008
#define IDC_EDIT_YCOORD                 1009
#define IDC_EDIT_ZCOORD                 1010
#define IDC_BUTTON_DEFINE_REPOSITION    1011
#define IDC_RADIO_RELATIVE              1012
#define IDC_BUTTON_REPOSITION2          1012
#define IDC_BUTTON_SYSPARAM             1012
#define IDC_RADIO_ABSOLUTE              1013
#define IDC_RADIO_CH2                   1013
#define IDC_RADIO_05M                   1013
#define IDC_STATICX                     1014
#define IDC_RADIO_CH4                   1014
#define IDC_RADIO_02MHz                 1014
#define IDC_STATICY                     1015
#define IDC_RADIO_CH6                   1015
#define IDC_RADIO_1MHz                  1015
#define IDC_STATICZ                     1016
#define IDC_RADIO_CH8                   1016
#define IDC_RADIO_FIL_DA1               1016
#define IDC_RADIO1                      1017
#define IDC_RADIO_CROSS                 1017
#define IDC_RADIO_CH1                   1017
#define IDC_RADIO_DEEPDRAW              1017
#define IDC_RADIO_1M                    1017
#define IDC_RADIO_DAC_ON                1017
#define IDC_RADIO_GATE_I_H              1017
#define IDC_RADIO_TCG_SOFT              1017
#define IDC_RADIO_MANUALLY_SELECT       1017
#define IDC_RADIO_STEPPING_CIRCUMFERENCE 1017
#define IDC_RADIO_CIRCUMFERENCE_STEPPER 1017
#define IDC_EDIT_XL                     1018
#define IDC_RADIO_RANGEDRAW             1018
#define IDC_RADIO2                      1018
#define IDC_XIANGDUI_CROOD              1018
#define IDC_RADIO_DAC_OFF               1018
#define IDC_RADIO_CH3                   1018
#define IDC_RADIO_GATE_I_L              1018
#define IDC_RADIO_HARDWARE              1018
#define IDC_RADIO_                      1018
#define IDC_RADIO_MOUSE_SELECT          1018
#define IDC_RADIO_RDA11                 1018
#define IDC_EDIT_YL                     1019
#define IDC_RADIO3                      1019
#define IDC_RADIO_FIRST_THRESHOLD_TIME  1019
#define IDC_RADIO_GATE_A_H              1019
#define IDC_RADIO_CH5                   1019
#define IDC_RADIO_DA_AMP1               1019
#define IDC_EDIT_ZL                     1020
#define IDC_RADIO_GATE_A_L              1020
#define IDC_RADIO_CH7                   1020
#define IDC_RADIO_DA_AMP2               1020
#define IDC_EDIT_XA                     1021
#define IDC_RADIO_GATE_B_H              1021
#define IDC_EDIT_YA                     1022
#define IDC_RADIO_GATE_B_L              1022
#define IDC_EDIT_ZA                     1023
#define IDC_RADIO_GATE_C_H              1023
#define IDC_EDIT_XREV                   1024
#define IDC_RADIO_GATE_C_L              1024
#define IDC_EDIT_YREV                   1025
#define IDC_EDIT_ZREV                   1026
#define IDC_EDIT_XMV                    1027
#define IDC_EDIT_YMV                    1028
#define IDC_EDIT_ZMV                    1029
#define IDC_EDIT_XKV                    1030
#define IDC_EDIT_YKV                    1031
#define IDC_EDIT_ZKV                    1032
#define IDC_EDIT_ZHIGH                  1033
#define IDC_CHECK_USE                   1034
#define IDC_EDIT_TIME                   1035
#define IDC_CHECK_KEDU                  1036
#define IDC_CHECK_PATH                  1037
#define IDC_CHECK_CATCH                 1038
#define IDC_RADIO_VER                   1039
#define IDC_EDIT_JIAN                   1040
#define IDC_EDIT_JIAN2                  1041
#define IDC_COMBO2                      1042
#define IDC_COMBO_GATE_NO               1042
#define IDC_COMBO_ONE_PROBE_TYPE        1042
#define IDC_COMBO_PIPE_CSAN1            1042
#define IDC_SLIDER_GATE_FRONT           1043
#define IDC_SLIDER_GATE_BACK            1044
#define IDC_SLIDER_GATE_PEAK            1045
#define IDC_EDIT_GATE_FRONT             1046
#define IDC_EDIT_GATE_BACK              1047
#define IDC_EDIT_GATE_PEAK              1048
#define IDC_BUTTON_GATE_COLOR           1049
#define IDC_CHECK1                      1050
#define IDC_CHECK_GATE_ISOPEN           1050
#define IDC_CHECK_ONESTEP               1050
#define IDC_CHECK_A_SCAN_SAVE           1050
#define IDC_CHECK_SAFE_AREA             1050
#define IDC_CHECK_ORIGIN                1050
#define IDC_CHECK                       1050
#define IDC_CHECK_SHOW_PROBE            1050
#define IDC_STATIC_DIPLAYCOLOR          1051
#define IDC_DIPLAYCOLOR                 1051
#define IDC_SLIDER_DELAY                1052
#define IDC_BUTTON_SETSTEP              1052
#define IDC_EDIT_DELAY                  1053
#define IDC_STATIC_STEP_X               1053
#define IDC_SLIDER_RANGE                1054
#define IDC_STATIC_STEP_Y               1054
#define IDC_EDIT_DELAY2                 1055
#define IDC_EDIT_RANGE                  1055
#define IDC_STATIC_STEP_Z               1055
#define IDC_SLIDER_PLUS                 1056
#define IDC_EDIT_STEP_X                 1056
#define IDC_EDIT_RANGE2                 1057
#define IDC_EDIT_PLUS                   1057
#define IDC_EDIT_STEP_Y                 1057
#define IDC_EDIT_TEMPC                  1057
#define IDC_EDIT3                       1058
#define IDC_EDIT_STEP_Z                 1058
#define IDC_EDIT_TEMPH                  1058
#define IDC_SLIDER_MTP_PEAK             1058
#define IDC_EDIT_THICK                  1058
#define IDC_EDIT_PROBE_NUM              1058
#define IDC_EDIT_DAC_AMP                1058
#define IDC_EDIT_MAIKUAN                1058
#define IDC_EDIT_SHANGLIAO_X            1058
#define IDC_EDIT_W2CORD                 1058
#define IDC_EDIT_W2COORD                1058
#define IDC_EDIT_ABCOORD                1058
#define IDC_EDIT_CCJJ                   1058
#define IDC_EDIT_B_SKETCH               1058
#define IDC_EDIT_LEFT_11_START          1058
#define IDC_EDIT_LEFT_1_START           1058
#define IDC_EDIT_Z_START                1058
#define IDC_EDIT_TEMPW                  1059
#define IDC_EDIT_MTP_PEAK               1059
#define IDC_EDIT_STEP_Z2                1059
#define IDC_EDIT_STEP_W1                1059
#define IDC_EDIT8                       1059
#define IDC_EDIT_SHANGLIAO_Y            1059
#define IDC_EDIT_STEP_A                 1059
#define IDC_EDIT_STEP_AB                1059
#define IDC_EDIT_LEFT_14_START          1059
#define IDC_EDIT_LEFT_2_START           1059
#define IDC_EDIT_MX                     1060
#define IDC_SLIDER_ZEROPOINT            1060
#define IDC_EDIT_STEP_B                 1060
#define IDC_EDIT_MY                     1061
#define IDC_EDIT_DELAY3                 1061
#define IDC_EDIT_ZEROPOINT              1061
#define IDC_EDIT_STEP_W                 1061
#define IDC_EDIT_V0                     1062
#define IDC_EDIT_REF_PLUS               1062
#define IDC_EDIT_STEP_W4                1062
#define IDC_EDIT_STEP_R                 1062
#define IDC_EDIT_V1                     1063
#define IDC_EDIT_FH                     1063
#define IDC_SLIDER_REF_PLUS             1063
#define IDC_EDIT_V2                     1064
#define IDC_EDIT_FW                     1064
#define IDC_EDIT_V3                     1065
#define IDC_EDIT_FMX                    1065
#define IDC_EDIT_V4                     1066
#define IDC_EDIT_FMY                    1066
#define IDC_EDIT_V5                     1067
#define IDC_EDIT_V6                     1068
#define IDC_EDIT_ROTATE                 1068
#define IDC_EDIT_XZOOM                  1068
#define IDC_EDIT_BEGIN_R                1068
#define IDC_EDIT_HIGH_LVBO              1068
#define IDC_EDIT_WAVE_SPEED             1068
#define IDC_EDIT_MIN_X                  1068
#define IDC_EDIT_USERNAME               1068
#define IDC_EDIT_PER_LENGTH             1068
#define IDC_EDIT_AUTOGAIN_AMP           1068
#define IDC_EDIT_GRAYVALUE              1068
#define IDC_EDIT_HARDWARE_VER           1068
#define IDC_EDIT_W1COORD                1068
#define IDC_EDIT_MIN_AREA               1068
#define IDC_EDIT_X1                     1068
#define IDC_EDIT_OffSET_X               1068
#define IDC_EDIT_RCOORD                 1068
#define IDC_EDIT_TASK_NAME              1068
#define IDC_EDIT_V7                     1069
#define IDC_EDIT2                       1069
#define IDC_EDIT_YZOOM                  1069
#define IDC_RADIO_INITPULSE             1069
#define IDC_EDIT_BEGIN_G                1069
#define IDC_EDIT_LOW_LVBO               1069
#define IDC_EDIT_MAX_X                  1069
#define IDC_EDIT_PASSWORD               1069
#define IDC_EDIT_PROBE_DISTANCE         1069
#define IDC_EDIT_DAC_RANGE              1069
#define IDC_EDIT_Y1                     1069
#define IDC_EDIT_OffSET_Y               1069
#define IDC_EDIT_BADMIN                 1069
#define IDC_EDIT_ACOORD                 1069
#define IDC_EDIT_WCOORD                 1069
#define IDC_EDIT_TARGETRABGE            1069
#define IDC_EDIT_AB_SKETCH              1069
#define IDC_EDIT_RIGHT_11_START         1069
#define IDC_EDIT_RIGHT_1_START          1069
#define IDC_EDIT_W_STOP                 1069
#define IDC_EDIT_TEST_HOLE_RANGE        1069
#define IDC_EDIT_SURFACE_COMP           1069
#define IDC_EDIT_V8                     1070
#define IDC_RADIO_FIRSTECHO             1070
#define IDC_EDIT_BEGIN_B                1070
#define IDC_EDIT_MIN_Y                  1070
#define IDC_EDIT_CONGDIE                1070
#define IDC_EDIT_Z1                     1070
#define IDC_EDIT_BADMAX                 1070
#define IDC_EDIT_ACOORD2                1070
#define IDC_EDIT_TEST_HOLE_AMP          1070
#define IDC_EDIT_V9                     1071
#define IDC_COMBO_CH_SI                 1071
#define IDC_EDIT_END_R                  1071
#define IDC_EDIT_MAX_Y                  1071
#define IDC_EDIT_X2                     1071
#define IDC_EDIT_V10                    1072
#define IDC_COMBO_CH_SAVG               1072
#define IDC_STATIC_X                    1072
#define IDC_EDIT_END_G                  1072
#define IDC_EDIT_Y2                     1072
#define IDC_EDIT_V11                    1073
#define IDC_STATIC_GRADIENT             1073
#define IDC_COMBO_CH_SAVG2              1073
#define IDC_COMBO_SYNC_FREQ             1073
#define IDC_EDIT_Z2                     1073
#define IDC_EDIT_V12                    1074
#define IDC_STATIC_Y                    1074
#define IDC_EDIT_END_B                  1074
#define IDC_EDIT_X3                     1074
#define IDC_EDIT_V13                    1075
#define IDC_STATIC_X3                   1075
#define IDC_STATIC_Z                    1075
#define IDC_EDIT_Y3                     1075
#define IDC_EDIT_V14                    1076
#define IDC_SPIN_FRONT                  1076
#define IDC_EDIT_Z3                     1076
#define IDC_EDIT_V15                    1077
#define IDC_SPIN_WIDTH                  1077
#define IDC_RADIO_2M                    1077
#define IDC_EDIT_X4                     1077
#define IDC_EDIT_V16                    1078
#define IDC_SPIN_GATE_PEAK              1078
#define IDC_RADIO_WIDE_BAMD             1078
#define IDC_EDIT_Y4                     1078
#define IDC_EDIT_V17                    1079
#define IDC_SPIN_MTP_PEAK               1079
#define IDC_RADIO_5M                    1079
#define IDC_EDIT18                      1079
#define IDC_EDIT_Z4                     1079
#define IDC_EDIT_V18                    1080
#define IDC_SPIN_ZEROPOINT              1080
#define IDC_RADIO_205M                  1080
#define IDC_EDIT_X5                     1080
#define IDC_EDIT_V19                    1081
#define IDC_SPIN_DELAY                  1081
#define IDC_RADIO_PRESSURE1             1081
#define IDC_EDIT_Y5                     1081
#define IDC_EDIT_V20                    1082
#define IDC_SPIN_RANGE                  1082
#define IDC_RADIO_PRESSURE2             1082
#define IDC_EDIT_Z5                     1082
#define IDC_RADIO_RDA12                 1082
#define IDC_EDIT_V21                    1083
#define IDC_SPIN8                       1083
#define IDC_SPIN_PLUS                   1083
#define IDC_RADIO_PRESSURE3             1083
#define IDC_EDIT_X6                     1083
#define IDC_RADIO_RDA22                 1083
#define IDC_EDIT_V22                    1084
#define IDC_RADIO_PRESSURE4             1084
#define IDC_SPIN_PLUS2                  1084
#define IDC_SPIN_REF_PLUS               1084
#define IDC_EDIT_Y6                     1084
#define IDC_EDIT_V23                    1085
#define IDC_RADIO_PLUS_HWAVE            1085
#define IDC_EDIT_Z6                     1085
#define IDC_EDIT27                      1086
#define IDC_EDIT_V24                    1086
#define IDC_RADIO_MINUS_HWAVE           1086
#define IDC_EDIT_X7                     1086
#define IDC_LIST_DAC                    1087
#define IDC_RADIO_FULL_WAVE             1087
#define IDC_EDIT_Y7                     1087
#define IDC_SCROLLBAR_AMP_LEVEL         1088
#define IDC_RADIO_RF                    1088
#define IDC_EDIT_Z7                     1088
#define IDC_SCROLLBAR_CUR_POS           1089
#define IDC_RADIO_LOW_IMPEDANCE         1089
#define IDC_EDIT_X8                     1089
#define IDC_STATIC_AMP_LEVEL            1090
#define IDC_RADIO_HIGH_IMPEDANCE        1090
#define IDC_EDIT_Y8                     1090
#define IDC_STATIC_CUR_POS              1091
#define IDC_RADIO1_HIGH_LVBO            1091
#define IDC_RADIO_HIGH_LVBO             1091
#define IDC_EDIT_Z8                     1091
#define IDC_RADIO_RDA21                 1091
#define IDC_STATIC_CUR_AMP              1092
#define IDC_RADIO_LOW_LVBO              1092
#define IDC_RADIO_WIDE_FIL_DA2          1092
#define IDC_STATIC_MAKE_DAC             1093
#define IDC_RADIO_BAND_LVBO             1093
#define IDC_RADIO_LOW_ERNERGY           1093
#define IDC_EDIT_AMP_LEVEL              1094
#define IDC_BUTTON_READ_PARAM           1094
#define IDC_RADIO_HIGH_ERNERGY          1094
#define IDC_EDIT_CUR_POS                1095
#define IDC_BUTTON_SAVE_AS_PARAM        1095
#define IDC_RADIO_LOW_OneSendOneRev     1095
#define IDC_EDIT_CUR_AMP                1096
#define IDC_BUTTON_OTHER_PARAM          1096
#define IDC_RADIO_HIGH_SelfSendSelfRev  1096
#define IDC_BUTTON_ADD_POINT            1097
#define IDC_STATIC_MODIFY_DAC           1098
#define IDC_STATIC_WDR_X                1098
#define IDC_BUTTON_DEL_ONE_POINT        1099
#define IDC_STATIC_WDR_Y                1099
#define IDC_COORD                       1099
#define IDC_BUTTON_DEL_ALL_POINT        1100
#define IDC_STATIC_WDR_X3               1100
#define IDC_STATIC_WDR_Z                1100
#define IDC_WIDTH                       1100
#define IDC_LONG                        1100
#define IDC_BUTTON_CHANGE_GAIN          1101
#define IDC_STATICWIDTH                 1101
#define IDC_EDIT_CHANGE_GAIN            1102
#define IDC_STATICHEIGHT                1102
#define IDC_BUTTON_DAC_CANCLE           1103
#define IDC_STATICDBVALUE               1103
#define IDC_STATIC_DAC_ENABLE           1104
#define IDC_BUTTON_SURFACE_CALC         1104
#define IDC_STATIC_DAC_SHOW             1105
#define IDC_BUTTON_SURFACE_DETAIL       1105
#define IDC_RADIO_DAC_STAT_ON           1106
#define IDC_LIST_SURFACE_DETAIL         1106
#define IDC_RADIO_DAC_STAT_OFF          1107
#define IDC_PLATEDRAWCTRL               1107
#define IDC_RADIO_DAC_SHOW_ON           1108
#define IDC_RADIO_DAC_SHOW_OFF          1109
#define IDC_STATIC_CURRENTDB            1109
#define IDC_BUTTON_READ_FILE            1110
#define IDC_STATIC_ZOOM                 1110
#define IDC_SCAN_INFO                   1111
#define IDC_RADIO_MAX_VALUE             1114
#define IDC_RADIO_MIN_VALUE             1115
#define IDC_RADIO_AVG_VALUE             1116
#define IDC_BUTTON_DRAW_PICTURE         1120
#define IDC_EDIT_GATE1_THRESHOLD        1124
#define IDC_EDIT_GATE2_THRESHOLD        1125
#define IDC_EDIT_GATE3_THRESHOLD        1126
#define IDC_EDIT_GATE4_THRESHOLD        1127
#define IDC_EDIT_BOUND_MIN              1129
#define IDC_EDIT_BOUND_MAX              1130
#define IDC_RADIO_SELECT_GATE1          1131
#define IDC_RADIO_SELECT_GATE2          1132
#define IDC_RADIO_SELECT_GATE3          1133
#define IDC_RADIO_SELECT_GATE4          1134
#define IDC_BUTTON1                     1135
#define IDC_BUTTON_MOVE_TO_FLAW         1135
#define IDC_SAVE_PATH_FILE              1135
#define IDC_BUTTON_SAVE_CSCAN_PICTURE   1135
#define IDC_BUTTON_                     1135
#define IDC_BUTTON_SAVE_PARAM           1135
#define IDC_BUTTON_DAC_AUTO_GAIN        1135
#define IDC_BUTTON_PROBE_LOCATION       1135
#define IDC_BUTTON_BADFONT              1135
#define IDC_BUTTON_CREATE               1135
#define IDC_BUTTON_CSCAN_REALTIME       1136
#define IDC_OPEN_PATH_FILE              1136
#define IDC_BUTTON5                     1136
#define IDC_BUTTON_STOP_CSCAN           1137
#define IDC_CHECK_MP_F_TIME             1137
#define IDC_CHECK_MP_M_TIME             1138
#define IDC_CHECK_MP_M_ALTITUDE         1139
#define IDC_CHECK_FP_F_TIME             1140
#define IDC_CHECK_FP_M_TIME             1141
#define IDC_CHECK7                      1142
#define IDC_CHECK_FP_M_ALTITUDE         1142
#define IDC_COMBO_PROBE_                1143
#define IDC_COMBO_PROBE_FREQ            1143
#define IDC_RADIO_MAX_AMP1              1144
#define IDC_RADIO_FIRST_AMP1            1145
#define IDC_RADIO_MAX_TIME1             1146
#define IDC_RADIO_MAX_THRESHOL_TIME1    1147
#define IDC_RADIO_FIRST_TIME1           1148
#define IDC_RADIO_FIRST_THRESHOLD_TIME1 1149
#define IDC_BUTTON_CSCAN_PARAM_SAVE     1150
#define IDC_BUTTON3                     1151
#define IDC_BUTTON_CSCAN_PARAM_READ     1151
#define IDC_BUTTON_GET_RECT             1151
#define IDC_BUTTON_DAC_CREATE           1151
#define IDC_BUTTON_DATE_SAVE            1151
#define IDC_BUTTON_LOAD                 1151
#define IDC_BUTTON_TAIL_DECREASE_PIPE_PARAM 1151
#define IDC_BUTTON                      1151
#define IDC_BUTTON_RESET                1151
#define IDC_BUTTON2                     1152
#define IDC_FILE_SAVE_AS                1152
#define IDC_BUTTON_DAC_ADD_POINT        1152
#define IDC_BUTTON_DEFAULT_COLOR1       1152
#define IDC_BUTTON_SAVETO_EXCEL         1152
#define IDC_BUTTON_PIPE_SET             1152
#define IDC_BUTTON_SAVE                 1152
#define IDC_BUTTON_COMPENSATE           1152
#define IDC_CHECK_CHANNEL1_SWITCH       1154
#define IDC_CHECK_GROUP1_SWITCH         1154
#define IDC_CHECK_CHANNEL2_SWITCH       1155
#define IDC_CHECK_GROUP2_SWITCH         1155
#define IDC_SLIDER1                     1156
#define IDC_SLIDER_RESTRAIN             1156
#define IDC_SLIDER_BSCAN_ORIGIN         1156
#define IDC_EDIT_RESTRAIN               1157
#define IDC_SLIDER_BSCAN_WIDTH          1157
#define IDC_SPIN_RESTRAIN               1158
#define IDC_EDIT_BSCAN_ORIGIN           1159
#define IDC_CHECK_CHANNEL3_SWITCH       1159
#define IDC_CHECK_GROUP3_SWITCH         1159
#define IDC_EDIT5                       1160
#define IDC_EDIT_BSCAN_WIDTH            1160
#define IDC_STATIC_HANHE_STATISTICS     1160
#define IDC_EDIT_SAFE_MINY              1160
#define IDC_EDIT_DINGLIANG              1160
#define IDC_CHECK_CHANNEL2_SWITCH2      1160
#define IDC_CHECK_CHANNEL4_SWITCH       1160
#define IDC_CHECK_GROUP4_SWITCH         1160
#define IDC_EDIT_C_SKETCH               1160
#define IDC_EDIT_LEFT_14_STOP           1160
#define IDC_EDIT_LEFT_2_STOP            1160
#define IDC_EDIT_DB_COMPENSATE_VALUE    1160
#define IDC_CHECK_SURFACE_STATISTICS    1161
#define IDC_STATIC_HANHE_RATE           1162
#define IDC_EDIT_SAFE_MINX              1162
#define IDC_EDIT_SAFE_MAXX              1163
#define IDC_EDIT_SAFE_MAXY              1164
#define IDC_STATIC_DAC_CREATE           1165
#define IDC_BUTTON_DAC_MODIFY_CONFIRM   1166
#define IDC_BUTTON_DAC_DELETE_POINT     1167
#define IDC_LIST_DAC_INFO               1168
#define IDC_BUTTON_DAC_MODIFY           1169
#define IDC_STATIC_SOFT_VER             1170
#define IDC_STATIC_DSP_VER              1171
#define IDC_STATIC_FPGA1_VER            1172
#define IDC_STATIC_FPGA2_VER            1173
#define IDC_EDIT_PINGDING               1173
#define IDC_STATIC_FPGA_VER3            1174
#define IDC_STATIC_FPGA3_VER            1174
#define IDC_EDIT_PANHUI                 1174
#define IDC_BUTTON_PREV_DAC_POINT       1175
#define IDC_BUTTON_NEXT_DAC_POINT       1176
#define IDC_EDIT4                       1177
#define IDC_EDIT_CURRENT_POINT_NUM      1177
#define IDC_EDIT_CHONGDIE_LENGTH        1177
#define IDC_EDIT_RE_FREQ                1177
#define IDC_EDIT_BC_SKETCH              1177
#define IDC_EDIT_LEFT_11_STOP           1177
#define IDC_EDIT_LEFT_1_STOP            1177
#define IDC_EDIT_Z_STOP                 1177
#define IDC_DAC_FILE_OPEN               1178
#define IDC_BUTTON_FILE_SAVE            1179
#define IDC_EDIT_DEFECT_SIZE            1180
#define IDC_EDIT__DEFECT_RANGE          1181
#define IDC_RADIO_FIRST_TIME            1185
#define IDC_RADIO_MAX_THRESHOL_TIME     1186
#define IDC_RADIO_MAX_TIME              1187
#define IDC_RADIO_FIRST_AMP             1188
#define IDC_RADIO_MAX_AMP               1189
#define IDC_RADIO_SCAN_TYPE_STEP        1190
#define IDC_LIST_RECT_POINTS            1190
#define IDC_RADIO_SCAN_TYPE_DEPTH       1191
#define IDC_LIST2                       1191
#define IDC_COMBO_PROBE_NUM             1192
#define IDC_COMBO_TWO_PROBE_TYPE        1193
#define IDC_BUTTON4                     1193
#define IDC_BUTTON_DISPLAY_RECT         1193
#define IDC_BUTTON_DEFAULT_COLOR2       1193
#define IDC_BUTTON_TABLE                1193
#define IDC_BUTTON_SAVE_ITEM            1193
#define IDC_COMBO4IDC_COMBO_THREE_PROBE_TYPE 1194
#define IDC_COMBO_THREE_PROBE_TYPE      1194
#define IDC_COMBO_MATERIAL              1194
#define IDC_COMBO_FOUR_PROBE_TYPE       1195
#define IDC_DATETIMEPICKER1             1195
#define IDC_COMBO3                      1198
#define IDC_COMBO_AXIS                  1198
#define IDC_COMBO_BADFONT               1198
#define IDC_COMBO_PIPE_CSCAN2           1198
#define IDC_RADIO_STEP_X                1199
#define IDC_RADIO_STEP_Y                1200
#define IDC_RADIO6                      1201
#define IDC_RADIO_STEP_Z                1201
#define IDC_RADIO_CIRCLE                1201
#define IDC_RADIO_SCAN_X                1202
#define IDC_RADIO_SCAN_Y                1203
#define IDC_RADIO_SACN_Z                1204
#define IDC_RADIO_SCAN_Z                1204
#define IDC_COMBO1                      1205
#define IDC_COMBO_PICTURE_MODE          1205
#define IDC_COMBO_WORK_MODE             1205
#define IDC_COMBO_AREA                  1205
#define IDC_COMBO_G11                   1205
#define IDC_BUTTON_W1_POSITIVE          1206
#define IDC_COMBO_G21                   1206
#define IDC_BUTTON_R_POSITIVE           1206
#define IDC_BUTTON_W1_REVERSE           1207
#define IDC_COMBO_G31                   1207
#define IDC_BUTTON_R_REVERSE            1207
#define IDC_BUTTON_W2_POSITIVE          1208
#define IDC_COMBO_G41                   1208
#define IDC_BUTTON_AB_POSITIVE          1208
#define IDC_BUTTON_W2_REVERSE           1209
#define IDC_COMBO_G12                   1209
#define IDC_BUTTON_AB_REVERSE           1209
#define IDC_COMBO_G22                   1210
#define IDC_COMBO_G32                   1211
#define IDC_BUTTON_A_POSITIVE           1212
#define IDC_COMBO_G42                   1212
#define IDC_BUTTON_W_POSITIVE           1212
#define IDC_BUTTON_A_REVERSE            1213
#define IDC_BUTTON_W_REVERSE            1213
#define IDC_BUTTON_B_POSITIVE           1214
#define IDC_BUTTON13                    1215
#define IDC_BUTTON_B_REVERSE            1215
#define IDC_MDSOCX1                     1216
#define IDC_MDSOCX                      1216
#define IDC_EDIT6                       1217
#define IDC_EDIT_SAFE_MAXZ              1217
#define IDC_EDIT_CD_SKETCH              1217
#define IDC_EDIT_RIGHT_14_STOP          1217
#define IDC_EDIT_RIGHT_2_STOP           1217
#define IDC_BUTTON_SAVE_DATA            1218
#define IDC_EDIT_R_SPEED                1219
#define IDC_STATIC_W1                   1220
#define IDC_EDIT_AB_SPEED               1220
#define IDC_STATIC_STEP_R               1221
#define IDC_EDIT_W_SPEED                1221
#define IDC_BUTTON_SHANGLIAO_POS        1222
#define IDC_BUTTON_CACULATE_VELOCITY    1222
#define IDC_RADIO_XMODE_ANGLE           1224
#define IDC_STATICW2                    1224
#define IDC_STATICW                     1224
#define IDC_RADIO5                      1225
#define IDC_RADIO_XMODE_PERIMETER       1225
#define IDC_STATICW3                    1225
#define IDC_RADIO_SCAN_W                1225
#define IDC_SLIDER_RE_FREQ              1226
#define IDC_STATIC_STEP_W               1226
#define IDC_SPIN1                       1227
#define IDC_SPIN_RE_FREQ                1227
#define IDC_STATIC_STEP_A               1227
#define IDC_STATIC_STEP_AB              1227
#define IDC_RADIO_VELOCITY_PICTURE      1228
#define IDC_STATIC_STEP_B               1228
#define IDC_RADIO_VELOCITY_REDUCE_PICTURE 1229
#define IDC_STATIC_W2                   1229
#define IDC_RADIO_SZK_PICTURE           1230
#define IDC_RADIO_MIDU_PICTURE          1231
#define IDC_BUTTON_CALCUATE_SHUAIJIAN   1233
#define IDC_BUTTON_CACULATE_SZK         1234
#define IDC_BUTTON_CACULATE_MIDU        1235
#define IDC_EDIT_AVE_VELOCITY           1236
#define IDC_EDIT_AVE_SHUAIJIAN          1237
#define IDC_EDIT_AVE_SZK                1238
#define IDC_EDIT_AVE_MIDU               1239
#define IDC_CHECK_GATE_I                1240
#define IDC_CHECK_GATE_A                1241
#define IDC_BUTTON_BINNARYSAVE          1241
#define IDC_CHECK_GATE_B                1242
#define IDC_CHECK2                      1242
#define IDC_CHECK_LOCK_PARAM            1242
#define IDC_CHECK_DISPLAY_PROBE         1242
#define IDC_CHECK_XY_REVERSE            1242
#define IDC_CHECK_TAILDECREASEPIPE      1242
#define IDC_CHECK_GATE_C                1243
#define IDC_BUTTON_HANHE_RATE           1244
#define IDC_STATIC_HANHE_STATI          1245
#define IDC_BUTTON_HANHE_CACULATE       1246
#define IDC_CHECK_CSCAN_SYNC            1247
#define IDC_STATIC_SURFACE_TITLE        1248
#define IDC_RADIO_RECT                  1249
#define IDC_RADIO7                      1250
#define IDC_RADIO_ELLIPSE               1250
#define IDC_RADIO_POLYGON               1251
#define IDC_BUTTON_ORIGIN               1252
#define IDC_STATIC_ORIGIN_X             1253
#define IDC_STATIC_ORIGIN_Y             1254
#define IDC_STATIC_GROUP1               1255
#define IDC_RADIO_POLYGON2              1255
#define IDC_STATIC_GROUP2               1256
#define IDC_STATIC_GROUP3               1257
#define IDC_STATIC_GROUP4               1258
#define IDC_BUTTON_DEF_COLOR0           1259
#define IDC_BUTTON_DEF_COLOR1           1260
#define IDC_BUTTON_DEF_COLOR2           1261
#define IDC_BUTTON_DEF_COLOR3           1262
#define IDC_BUTTON_DEF_COLOR4           1263
#define IDC_BUTTON_DEF_COLOR5           1264
#define IDC_CHECK_ZHUSHI                1265
#define IDC_RADIO_ZHUSHI_RECT           1266
#define IDC_RADIO_ZHUSHI_CIRCLE         1267
#define IDC_RADIO_ZHUSHI_ELLIPSE        1268
#define IDC_RADIO_ZHUSHI_POLYGON        1269
#define IDC_BUTTON_TCG_CREATE           1270
#define IDC_BUTTON_TCG_ADD_POINT        1271
#define IDC_BUTTON_PREV_TCG_POINT       1272
#define IDC_EDIT_TCG_CURRENT_POINT_NUM  1273
#define IDC_BUTTON_NEXT_TCG_POINT       1274
#define IDC_BUTTON_TCG_DELETE_POINT     1275
#define IDC_EDIT_TCG_RANGE              1276
#define IDC_EDIT_TCG_AMP                1277
#define IDC_BUTTON_TCG_MODIFY_CONFIRM   1278
#define IDC_RADIO_TCG_ON                1279
#define IDC_RADIO_TCG_OFF               1280
#define IDC_TCG_FILE_OPEN               1281
#define IDC_BUTTON_TCG_FILE_OPEN        1281
#define IDC_BUTTON_TCG_FILE_SAVE        1282
#define IDC_LIST_TCG                    1283
#define IDC_BUTTON_TCG_MODIFY_CONFIRM2  1284
#define IDC_BUTTON_TCG_SRAM_MODIFY      1284
#define IDC_RADIO_GATE_ABOVE            1285
#define IDC_RADIO_GATE_BELOW            1286
#define IDC_CHECK3                      1286
#define IDC_CHECK_EXTENSION             1286
#define IDC_CHECK_CHANGE_Z_W            1286
#define IDC_CHECK_BADFLAG               1287
#define IDC_BTN_BADSYMBOL               1288
#define IDC_BUTTON_DEFECT               1293
#define IDC_CHECK_DEFINE1               1296
#define IDC_CHECK_DEFINE2               1297
#define IDC_CHECK_DEFINE3               1298
#define IDC_COMBO4                      1298
#define IDC_COMBO_STEP_MODE             1298
#define IDC_COMBO_SYMBOL1               1299
#define IDC_STATIC_W                    1299
#define IDC_COMBO_SYMBOL2               1300
#define IDC_STATIC_B                    1300
#define IDC_COMBO_SYMBOL3               1301
#define IDC_STATIC_BVALUE               1301
#define IDC_STATIC_AB                   1301
#define IDC_CHECK_GATE_ADJUST           1302
#define IDC_STATICAB                    1302
#define IDC_STATICR                     1303
#define IDC_BUTTON_CREATE_ITEM          1304
#define IDC_BUTTON_DEL_ITEM             1305
#define IDC_BUTTON_CREATE_CUBE          1306
#define IDC_LIST_TASK_ITEMS             1307
#define IDC_STATIC_TASK                 1308
#define IDC_EDIT_ITEM_NAME              1309
#define IDC_EDIT_WATER_DISTANCE         1310
#define IDC_EDIT_AB_RADIUS              1311
#define IDC_EDIT_W_RADIUS               1312
#define IDC_BUTTON_GET_WATER_DISTANCE   1313
#define IDC_STATIC_RUN_STATE            1314
#define IDC_LIST_FLAW_LIST              1315
#define IDC_LIST_CUSTUM_FLAW            1316
#define IDC_RADIO_CUSTUM_SURFACE        1317
#define IDC_RADIO_GENERAL_SURFACE       1318
#define IDC_EDIT_DB                     1319
#define IDC_EDIT_11_MIN                 1319
#define IDC_EDIT_JZNUM                  1319
#define IDC_EDIT_A_SKETCH               1319
#define IDC_EDIT_RIGHT_14_START         1319
#define IDC_EDIT_RIGHT_2_START          1319
#define IDC_EDIT_11_MAX                 1320
#define IDC_CHECK4                      1320
#define IDC_CHECK_REAL_SCALE            1320
#define IDC_EDIT_14_MIN                 1321
#define IDC_BUTTON_PALETTE              1321
#define IDC_EDIT_SKETCH                 1321
#define IDC_EDIT_D_SKETCH               1321
#define IDC_EDIT_17_MIN                 1322
#define IDC_BUTTON_IMPORT_PALETTE       1322
#define IDC_EDIT_STARTPOSITION          1322
#define IDC_EDIT_18_MIN                 1323
#define IDC_BUTTON_DEFAULT_COLOR3       1323
#define IDC_EDIT_ANGLE                  1323
#define IDC_EDIT_DOTTEDWIDTH            1324
#define IDC_EDIT_RIGHT_11_STOP          1325
#define IDC_EDIT_RIGHT_1_STOP           1325
#define IDC_EDIT_14_MIN2                1325
#define IDC_EDIT_WEIJIAN_W1             1325
#define IDC_EDIT_14_MAX                 1327
#define IDC_EDIT_W_START                1327
#define IDC_EDIT_17_MAX                 1328
#define IDC_BUTTON_INSTALL              1328
#define IDC_EDIT_18_MAX                 1329
#define IDC_STATIC_                     1329
#define IDC_STATIC_TRANSVERSE_START     1329
#define IDC_STATIC_TRANSVERSE_STOP      1330
#define IDC_STATIC_VERTICAL_START       1331
#define IDC_STATIC_VERTICAL_STOP        1332
#define IDC_RADIO_Z_AXIS_STEPPER        1333
#define IDC_RADIO4                      1334
#define IDC_RADIO_STEP_W                1334
#define IDC_ANIMATE1                    1335
#define IDC_STATIC_SKETCH               1336
#define IDC_SLIDER_SPI_DATA             1339
#define IDC_EDIT_SPI_DATA               1340
#define IDC_SPIN_SPI_DATA               1341
#define IDC_EDIT1                       1342
#define IDC_EDIT_MID_VALUE              1342
#define IDC_CHECK5                      1343
#define IDC_LOCK_PARAM                  1344
#define IDC_BUTTON6                     1345
#define IDC_BUTTON_BACKGROUND_COLOR     1346
#define IDC_STATIC_BACK_COLOR           1347
#define IDC_EDIT_MIN_AMP                1348
#define IDC_EDIT_MAX_AMP                1349
#define IDC_BUTTON_GETASCAN             11930
#define ID_VIEW_CUSTOMIZE               32770
#define ID_32771                        32771
#define ID_PATH_VIEW                    32772
#define ID_A_SCAN_VIEW                  32773
#define ID_C_SCAN_VIEW                  32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_START_A_SCAN                 32777
#define ID_STOP_A_SCAN                  32778
#define IDM_CHANNEL                     32779
#define IDM_CHANNEL_PANEL               32780
#define IDM_MECHANICAL_CONTROL          32781
#define ID_VIEW_MECHANICALCONTROL       32782
#define ID_DRAW_DAO                     32783
#define ID_DRAW_SELECT                  32784
#define ID_DRAW_HOLE                    32785
#define ID_DRAW_LINE                    32786
#define ID_DRAW_ARC                     32787
#define ID_DRAW_ARC_CENETR              32788
#define ID_DRAW_ARCLINE                 32789
#define ID_DRAW_CIRCLE_SAN              32790
#define ID_DRAW_CIRCLE                  32791
#define ID_DRAW_RECT                    32792
#define ID_DRAW_ELLIPSE                 32793
#define ID_DRAW_POLYGON                 32794
#define ID_DRAW_RUNWAY                  32795
#define ID_VIEW_SHI                     32796
#define ID_VIEW_TU                      32797
#define ID_VIEW_WINDOW                  32798
#define ID_TOOL_CAN                     32799
#define ID_TOOL_COLOR                   32800
#define ID_TOOL_JXIAN                   32801
#define ID_TOOL_JPIAN                   32802
#define ID_EDIT_SHAI                    32806
#define ID_EDIT_FAN                     32807
#define ID_EDIT_MIRROR                  32808
#define ID_EDIT_ROTA                    32809
#define ID_32810                        32810
#define ID_32811                        32811
#define ID_32812                        32812
#define ID_32813                        32813
#define ID_TOOL_EDIT                    32814
#define ID_TOOL_RESET                   32815
#define ID_TOOL_RUN                     32816
#define ID_32817                        32817
#define ID_NEW_FILE                     32818
#define ID_VIEW_CSCAN_PARAM             32819
#define ID_EDIT_FANSSFSDFSDFD           32821
#define IDM_VIEW_STANDARD               32822
#define IDM_VIEW_DRAW                   32823
#define IDM_VIEW_DRAW_BAR               32824
#define IDM_VIEW_STANDARD_BAR           32825
#define IDM_VIEW_BAR                    32826
#define ID_32827                        32827
#define ID_CSCAN_PARAM                  32828
#define ID_32829                        32829
#define ID_DAC32830                     32830
#define ID_DAC32831                     32831
#define ID_DAC_USER_DEFINE              32832
#define ID_DAC_STANDARD                 32833
#define ID_32834                        32834
#define ID_FEATURE_INFO                 32835
#define ID_32836                        32836
#define ID_DECOMPOSE                    32837
#define ID_ROTATE_IMAGE                 32838
#define ID_EMD_FILE_SAVE                32839
#define ID_EMD_FILE_OPEN                32840
#define ID_EMD_NEW_FILE                 32841
#define ID_32842                        32842
#define ID_32843                        32843
#define ID_SAVE_DATA_DEFINE             32844
#define ID_32845                        32845
#define ID_SAVE_A_SCAN                  32846
#define ID_32847                        32847
#define ID_C_SCAN_OVERVIEW              32848
#define ID_32849                        32849
#define ID_CSCAN_SMOOTH                 32850
#define ID_32851                        32851
#define ID_CSCAN_MF                     32852
#define ID_C_MICROSCOPE                 32853
#define ID_C_SCAN_MICROSCOPE            32854
#define ID_32855                        32855
#define ID_UNIT_SET                     32856
#define ID_SET_UNIT                     32857
#define ID_RULER                        32858
#define ID_BOX                          32859
#define ID_ELLIPSE                      32860
#define ID_32861                        32861
#define ID_MEASURE_TURN                 32862
#define ID_MEASURE_ON_OFF               32863
#define ID_32864                        32864
#define ID_RULER_MEASURE                32865
#define ID_TRIANGLE_MEASURE             32866
#define ID_ELLIPSE_MEASURE              32867
#define ID_CSCAN_RULER_MEASURE          32869
#define ID_32870                        32870
#define ID_DAC_CURVE                    32871
#define ID_32872                        32872
#define ID_B_SCAN_VIEW                  32873
#define ID_IP_CONFIG                    32874
#define ID_TOOL_PMOVE                   32876
#define ID_DATA_DIRECTORY_SET           32877
#define ID_32878                        32878
#define ID_CSCAN_PARAM2                 32879
#define ID_32880                        32880
#define ID_C_SCAN_VIEW2                 32881
#define ID_32882                        32882
#define ID_START_MONITOR_DATA           32883
#define ID_32884                        32884
#define ID_STOP_MONITOR_DATA            32885
#define ID_32886                        32886
#define ID_START_FEATURE_DATA           32887
#define ID_STOP_FEATURE_DATA            32888
#define ID_32889                        32889
#define ID_ProbeSet                     32890
#define ID_PROBE_SET                    32891
#define ID_POLYGON_MEASURE              32892
#define ID_NOTE_EDIT                    32893
#define ID_NOTE_DELETE                  32894
#define ID_TCG_CURVE                    32895
#define ID_BUTTON_READ_PARAM            32897
#define ID_BTN_OPEN_PATHFILE            32898
#define ID_BTN_SAVE_DATA                32899
#define ID_BUTTON_SAVE_PARAM            32900
#define ID_CHANNEL_TOOLBAR              32901
#define ID_MECHANICAL_TOOLBAR           32902
#define ID_CSCANPARAM_TOOLBAR           32903
#define ID_BTN_SAVE_PATHFILE            32904
#define ID_DUMMY_STANDARDTOOLBAR        32905
#define ID_BTN_READ_FILE                32906
#define ID_DUMMY_CUSTOMIZE              32907
#define ID_BTN_SAVE_CPARAM              32908
#define ID_BTN_READ_CPARAM              32909
#define ID_BTN_READ_PARAM               32910
#define ID_BTN_SAVE_PARAM               32911
#define ID_APP_HELP                     32912
#define ID_TASK_TOOLBAR                 32912
#define ID_32913                        32913
#define IDM_CSCAN_PARAM                 32914
#define IDM_TASK_PANEL                  32915
#define ID_32916                        32916
#define ID_32917                        32917
#define ID_CUSTUM_SURFACE_ADD           32918
#define ID_CUSTUM_SURFACE_DEL           32919
#define ID_32920                        32920
#define ID_SEL_SURFACE_CENTER           32921
#define ID_32922                        32922
#define ID_SEL_SURFACE_EDGE             32923
#define IDC_TAIL_DECREASE_PIPE_PARAM    32924
#define NOISE_REDUCTION                 32925
#define ID_NOISE_REDUCTION              32926
#define IDC_TAIL_DECREASE_PIPE_UNFOLD   32927
#define ID_32928                        32928
#define ID_PART_                        32929
#define ID_PART_GAN                     32930
#define ID_PART_GAIN                    32931
#define ID_PART_GAIN_COMPEN             32932
#define ID_PART_GAIN_COMPENCATE         32933
#define ID_PART_GAIN_COMPENSATE         32934
#define ID_PART_GAIN_COMPENSATE_SITE    32935
#define ID_32936                        32936
#define ID_DUPLICATE_DRAW_ONCE          32937
#define ID_32938                        32938
#define ID_32939                        32939
#define ID_CMD_CONNECT                  32940
#define ID_CMD_CLOSE                    32941
#define ID_32942                        32942
#define ID_CMD_S_CONNECT                32943
#define ID_CMD_S_CLOSE                  32944
#define ID_A_SCAN_DATA                  32945
#define ID_A_SCAN_DATA_START            32946
#define ID_A_SCAN_DATA_STOP             32947

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        214
#define _APS_NEXT_COMMAND_VALUE         32948
#define _APS_NEXT_CONTROL_VALUE         1343
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
